#!/usr/bin/env python3
# Build a complete init.sql from schema dump + seed data dump.
#
# This script:
# 1. Reads the schema dump (01_schema.sql)
# 2. Reads the seed data dump (02_seed_data.sql)
# 3. Removes pg_dump noise (restrict, unrestrict lines, etc.)
# 4. Adds alembic_version stamp
# 5. Outputs a single clean init.sql
#
# Usage:
#     python scripts/build_init_sql.py
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
INIT_DB_DIR = ROOT / "docker" / "init-db"
SCHEMA_FILE = INIT_DB_DIR / "01_schema.sql"
SEED_FILE = INIT_DB_DIR / "02_seed_data.sql"
OUTPUT_FILE = INIT_DB_DIR / "init.sql"

# Lines to strip from pg_dump output
STRIP_PATTERNS = [
    r"^\\restrict\b",
    r"^\\unrestrict\b",
    r"^-- Dumped from",
    r"^-- Dumped by",
    r"^-- PostgreSQL database dump",
    r"^-- PostgreSQL database dump complete",
]
STRIP_RE = re.compile("|".join(f"({p})" for p in STRIP_PATTERNS))


def clean_dump(lines: list[str]) -> list[str]:
    # Remove pg_dump noise lines.
    out = []
    for line in lines:
        stripped = line.rstrip("\n").rstrip("\r")
        if STRIP_RE.match(stripped):
            continue
        out.append(line)
    return out


def build():
    if not SCHEMA_FILE.exists():
        print(f"ERROR: {SCHEMA_FILE} not found. Run pg_dump first.")
        sys.exit(1)
    if not SEED_FILE.exists():
        print(f"ERROR: {SEED_FILE} not found. Run pg_dump first.")
        sys.exit(1)

    schema_lines = SCHEMA_FILE.read_text(encoding="utf-8").splitlines(keepends=True)
    seed_lines = SEED_FILE.read_text(encoding="utf-8").splitlines(keepends=True)

    schema_clean = clean_dump(schema_lines)
    seed_clean = clean_dump(seed_lines)

    with OUTPUT_FILE.open("w", encoding="utf-8", newline="\n") as f:
        # Header
        f.write("-- =============================================================\n")
        f.write("-- Taxja Database Initialization Script\n")
        f.write("-- Generated by scripts/build_init_sql.py\n")
        f.write("--\n")
        f.write("-- This file creates all tables, indexes, constraints,\n")
        f.write("-- and inserts seed data for reference tables.\n")
        f.write("--\n")
        f.write("-- Usage:\n")
        f.write("--   psql -U taxja -d taxja -f init.sql\n")
        f.write("--   OR place in docker-entrypoint-initdb.d/ for auto-init\n")
        f.write("-- =============================================================\n\n")

        # Schema
        f.write("-- =============================================================\n")
        f.write("-- PART 1: Schema (tables, types, indexes, constraints)\n")
        f.write("-- =============================================================\n\n")
        f.writelines(schema_clean)

        # Seed data
        f.write("\n\n-- =============================================================\n")
        f.write("-- PART 2: Seed Data (reference/configuration tables)\n")
        f.write("-- =============================================================\n\n")
        f.writelines(seed_clean)

        # Alembic version stamp
        f.write("\n\n-- =============================================================\n")
        f.write("-- PART 3: Alembic version stamp\n")
        f.write("-- Mark the database as fully migrated so Alembic won't\n")
        f.write("-- try to re-run migrations on an already-initialized DB.\n")
        f.write("-- =============================================================\n\n")
        f.write("INSERT INTO public.alembic_version (version_num)\n")
        f.write("  VALUES ('068_resync_doctypes')\n")
        f.write("  ON CONFLICT DO NOTHING;\n")

    size = OUTPUT_FILE.stat().st_size
    print(f"OK: {OUTPUT_FILE} generated ({size:,} bytes)")


if __name__ == "__main__":
    build()
